// Todo App - Sample Project
// Generated by Gemini AI Autonomous Team

class TodoApp {
    constructor() {
        this.todos = [];
        this.init();
    }

    init() {
        console.log('Todo App initialized');
        console.log('This is a sample project created by the Claude-Gemini Integration System');
    }

    addTodo(task) {
        const todo = {
            id: Date.now(),
            task: task,
            completed: false,
            createdAt: new Date()
        };
        this.todos.push(todo);
        return todo;
    }

    completeTodo(id) {
        const todo = this.todos.find(t => t.id === id);
        if (todo) {
            todo.completed = true;
            todo.completedAt = new Date();
        }
        return todo;
    }

    getTodos() {
        return this.todos;
    }

    getCompletedTodos() {
        return this.todos.filter(todo => todo.completed);
    }

    getPendingTodos() {
        return this.todos.filter(todo => !todo.completed);
    }
}

// Sample usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = TodoApp;
} else {
    // Browser environment
    console.log('Todo App ready for use');
    
    // Example usage:
    // const app = new TodoApp();
    // app.addTodo('Complete Claude-Gemini integration');
    // app.addTodo('Test MCP server functionality');
    // console.log(app.getTodos());
}